language: node_js

node_js:
    - '10'

cache:
    directories:
        - 'node_modules'

install:
    - npm install

script:
    - npm lint --fix

before_deploy:
    - npm install now --no-save

deploy:
    - provider: script
      script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
      skip_cleanup: true
      on:
          master: true
